### ISSUE TITLE
Is it ok to update packages to latest and then build solid standalone again?

### ISSUE THREAD

**Issue by MadadiSaeed** [ryansolid/solid-standalone#3]
Hi. I am using solid standalone to develop a simple app but I noticed the version number did not match with solid latest version. So is it OK to update package.json myself and build solid standalone again?

**Comment by ryansolid** [comment]
Yeah it's just a build configuration so it should be fine. Update to the latest hyper-dom-expressoins and lit-dom-expression packages also. I often miss updating this one on smaller releases but I can make a new version myself in a couple hours as well.

**Comment by ryansolid** [comment]
Ok I've updated the repo and published to npm.
